server:
  port: 8081
  error:
    path: /error
  servlet:
    session:
      timeout: 30m
      context-path: /mango
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mangodb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: root
      password: root
      filters: stst,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-perpared-statement-per-connection-size: 20
  #定义监控资源
  devtools:
    devtools:
        restart:
          enabled: true  #设置开启热部署
          additional-paths: src/main/java #重启目录
          exclude: WEB-INF/**
        freemarker:
          cache: false    #页面不加载缓存，修改即时生效
#获取mapper.xml
mybatis:
  mapper-locations: classpath:**/*.xml

